// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrKRLl7Y2EM5KQl5EQnKAiMd-8jh7hJWE',
    appId: '1:869065040084:web:0ca4cf487c66afc3b11b41',
    messagingSenderId: '869065040084',
    projectId: 'safe-flare',
    authDomain: 'safe-flare.firebaseapp.com',
    databaseURL: 'https://safe-flare-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'safe-flare.appspot.com',
    measurementId: 'G-KVGWJHL4VT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAr3aPM5bc5RiFgXz5p3J2dHzB8ph4dhIk',
    appId: '1:869065040084:android:67de8e8c908ed03eb11b41',
    messagingSenderId: '869065040084',
    projectId: 'safe-flare',
    databaseURL: 'https://safe-flare-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'safe-flare.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBL2FbrshEGdf7R6730LQhKypfspFzuA7A',
    appId: '1:869065040084:ios:b186cf0a13160ff1b11b41',
    messagingSenderId: '869065040084',
    projectId: 'safe-flare',
    databaseURL: 'https://safe-flare-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'safe-flare.appspot.com',
    iosClientId: '869065040084-gh9sj146gmok16rmck74koklbpfn5ppa.apps.googleusercontent.com',
    iosBundleId: 'com.example.safeFlare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBL2FbrshEGdf7R6730LQhKypfspFzuA7A',
    appId: '1:869065040084:ios:952a3599d5dcb48bb11b41',
    messagingSenderId: '869065040084',
    projectId: 'safe-flare',
    databaseURL: 'https://safe-flare-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'safe-flare.appspot.com',
    iosClientId: '869065040084-4gb030arf130qb8phs2b2cn80ua3b0cu.apps.googleusercontent.com',
    iosBundleId: 'com.example.safeFlare.RunnerTests',
  );
}
